import{S as i,i as u}from"./assets/vendor-9310f15c.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const f=document.querySelector(".gallery");function d(o){const e=o.reduce((s,a)=>s+`<li class="gallery-item">
              <a href=${a.largeImageURL}> 
              <img class="gallery-img" src =${a.webformatURL} alt=${a.tags}/>
              </a>
              <div class="gallery-text-box">
                <p>Likes: <span class="text-value">${a.likes}</span></p>
                <p>views: <span class="text-value">${a.views}</span></p>
                <p>comments: <span class="text-value">${a.comments}</span></p>
                <p>downloads: <span class="text-value">${a.downloads}</span></p>
              </div>
          </li>`,"");f.innerHTML=e}function m(o){return fetch(`https://pixabay.com/api/?${o}`).then(e=>{if(!e.ok)throw new Error(e.statusText);return e.json()})}const p=document.querySelector(".form"),y=document.querySelector(".gallery"),c=document.querySelector(".loader"),l={key:"12371278-ee82e7e687c0227bfbef9a885",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0},g=new i(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0});function h(){y.innerHTML=""}function L(){c.style.display="block"}function b(){c.style.display="none"}function v(o){return m(o).then(({hits:e})=>{e.length>0?(d(e),g.refresh()):u.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})}).catch(e=>{console.log(e.message)}).finally(()=>{b()})}p.addEventListener("submit",o=>{o.preventDefault(),h(),L(),l.q=o.target.elements.search.value.trim();const e=new URLSearchParams(l);v(e),o.currentTarget.reset()});
//# sourceMappingURL=commonHelpers.js.map
