import{S as u,i as l}from"./assets/vendor-9310f15c.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerpolicy&&(t.referrerPolicy=r.referrerpolicy),r.crossorigin==="use-credentials"?t.credentials="include":r.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(r){if(r.ep)return;r.ep=!0;const t=s(r);fetch(r.href,t)}})();const f=document.querySelector(".gallery");function d(o){const e=o.reduce((s,a)=>s+`<li class="gallery-item">
              <a href=${a.largeImageURL}> 
              <img class="gallery-img" src =${a.webformatURL} alt=${a.tags}/>
              </a>
              <div class="gallery-text-box">
                <p>Likes: <span class="text-value">${a.likes}</span></p>
                <p>views: <span class="text-value">${a.views}</span></p>
                <p>comments: <span class="text-value">${a.comments}</span></p>
                <p>downloads: <span class="text-value">${a.downloads}</span></p>
              </div>
          </li>`,"");f.innerHTML=e}function m(o){return fetch(`https://pixabay.com/api/?${o}`).then(e=>{if(!e.ok)throw new Error(e.statusText);return e.json()})}const p=document.querySelector(".form"),y=document.querySelector(".gallery"),i=document.querySelector(".loader"),c={key:"12371278-ee82e7e687c0227bfbef9a885",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0},g=new u(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0});function h(){y.innerHTML=""}function L(){i.style.display="block"}function b(){i.style.display="none"}function v(o){return m(o).then(({hits:e})=>{e.length>0?(d(e),g.refresh()):l.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})}).catch(e=>{l.error({position:"topRight",message:`Sorry there was an error: ${e}`})}).finally(()=>{b()})}p.addEventListener("submit",o=>{o.preventDefault(),h(),L(),c.q=o.target.elements.search.value.trim();const e=new URLSearchParams(c);v(e),o.currentTarget.reset()});
//# sourceMappingURL=commonHelpers.js.map
